// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhSBGjfv63u3xtGzfgzyB1qFZMbOUsF8',
    appId: '1:342125641718:web:f0f01237848e2fd881d1d7',
    messagingSenderId: '342125641718',
    projectId: 'doctor-appointment-app-270ff',
    authDomain: 'doctor-appointment-app-270ff.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-270ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaei2cwbBJ10uNknF_qxJYHLzSG_K4duU',
    appId: '1:342125641718:android:254ccc02a4cedb8181d1d7',
    messagingSenderId: '342125641718',
    projectId: 'doctor-appointment-app-270ff',
    storageBucket: 'doctor-appointment-app-270ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr6Skx70es1I7wxjYI97TQSuJjkejaZBY',
    appId: '1:342125641718:ios:bee3c0c84f7fc22a81d1d7',
    messagingSenderId: '342125641718',
    projectId: 'doctor-appointment-app-270ff',
    storageBucket: 'doctor-appointment-app-270ff.appspot.com',
    iosClientId: '342125641718-b6m5for792fh2omdqsjad11gkm1s2j7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr6Skx70es1I7wxjYI97TQSuJjkejaZBY',
    appId: '1:342125641718:ios:bee3c0c84f7fc22a81d1d7',
    messagingSenderId: '342125641718',
    projectId: 'doctor-appointment-app-270ff',
    storageBucket: 'doctor-appointment-app-270ff.appspot.com',
    iosClientId: '342125641718-b6m5for792fh2omdqsjad11gkm1s2j7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointement',
  );
}
